[[headers]]
  for = "/*"
    [headers.values]
      Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self'; font-src 'self' data:; connect-src 'self' https://script.google.com https://script.googleusercontent.com;"
